"""empty message

Revision ID: 8c8428ca5710
Revises: 942e266400af
Create Date: 2021-05-13 20:52:03.256087

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c8428ca5710'
down_revision = '942e266400af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_table', sa.Column('quiz_unlocked', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_table', 'quiz_unlocked')
    # ### end Alembic commands ###
