"""add module table

Revision ID: d63717527b10
Revises: 94c12ac034aa
Create Date: 2021-05-11 22:39:03.447855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd63717527b10'
down_revision = '94c12ac034aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('moduleset',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('number_of_questions', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('questionset')
    op.add_column('current_question', sa.Column('moduleset_id', sa.Integer(), nullable=True))
    op.drop_constraint(None, 'current_question', type_='foreignkey')
    op.create_foreign_key(None, 'current_question', 'moduleset', ['moduleset_id'], ['id'])
    op.drop_column('current_question', 'questionset_id')
    op.add_column('score', sa.Column('moduleset_id', sa.Integer(), nullable=True))
    op.drop_constraint(None, 'score', type_='foreignkey')
    op.create_foreign_key(None, 'score', 'moduleset', ['moduleset_id'], ['id'])
    op.drop_column('score', 'questionset_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('score', sa.Column('questionset_id', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'score', type_='foreignkey')
    op.create_foreign_key(None, 'score', 'questionset', ['questionset_id'], ['id'])
    op.drop_column('score', 'moduleset_id')
    op.add_column('current_question', sa.Column('questionset_id', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'current_question', type_='foreignkey')
    op.create_foreign_key(None, 'current_question', 'questionset', ['questionset_id'], ['id'])
    op.drop_column('current_question', 'moduleset_id')
    op.create_table('questionset',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=64), nullable=True),
    sa.Column('number_of_questions', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('moduleset')
    # ### end Alembic commands ###
